# Python Numpy Tutorial #1

본 페이지는 한림대학교 딥러닝이해및활용(712031) 수업에서 학생들의 Python 학습을 위해 만든 페이지입니다. 

# NumPy 

In [1]:
import numpy as np
import matplotlib.pyplot as plt

### List 형태의 배열

In [ ]:
a = [1, 2, 3]

In [ ]:
print(a)

### Numpy 사용한 배열

In [ ]:
a = np.array([1, 2, 3])

In [ ]:
print(a)

In [ ]:
a.shape

Create a vector with values ranging from 0 to 8 (총 9개)

In [ ]:
Z = np.arange(9)
print(Z)

Create a vector with values ranging from 10 to 19

In [ ]:
Z = np.arange(10,20)
print(Z)

In [ ]:
b = np.array([[1,2,3],[4,5,6]])   # rank가 2인 배열 생성
print(b.shape)                     # 출력 "(2, 3)"
print(b[0, 0], b[0, 1], b[1, 0])   # 출력 "1 2 4"

 * 순서 뒤집기 
 
 Reverse a vector : first element becomes last

In [ ]:
Z = np.arange(10)
print(Z)

In [ ]:
Z = Z[::-1]
print(Z)

### Axis / axes

* the nth coordinate to index an array in Numpy. 
* multidimensional arrays can have one index per axis.

In [ ]:
a = np.array([[1, 2], [3, 4]])
print(a)

Axis를 지정하지 않으면 전체 평균을 구하게 됨

In [ ]:
np.mean(a) 

Axis 0 방향 (↓)

In [ ]:
np.mean(a, axis=0)

In [ ]:
np.sum(a, axis=0)

Axis 1 방향 (→)

In [ ]:
np.mean(a, axis=1)

In [ ]:
np.sum(a, axis=1)

### Slicing and dicing
Slicing and Dicing refers to a way of segmenting, viewing and comprehending data in a database. 
Large blocks of data is cut into smaller segments and the process is repeated until the correct level of detail is achieved for proper analysis. 

In [2]:
a = np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [3]:
##(start:stop:step)
a[2:7:2] 

array([2, 4, 6])

In [4]:
a[4:]

array([4, 5, 6, 7, 8, 9])

In [5]:
a[:4]

array([0, 1, 2, 3])

In [7]:
a = np.array([[1,2,3],[3,4,5],[4,5,6]]) 
print(a)

[[1 2 3]
 [3 4 5]
 [4 5 6]]


In [8]:
a.shape

(3, 3)

In [11]:
# Returns array of items in the second column 
a[...,1]

array([2, 4, 5])

In [12]:
# Will slice all items from the second row 
a[1,...] 

array([3, 4, 5])

In [13]:
# Will slice all items from column 1 onwards 
a[...,1:]

array([[2, 3],
       [4, 5],
       [5, 6]])

In [15]:
a[1:3,...]

array([[3, 4, 5],
       [4, 5, 6]])

In [17]:
# Slicing using advanced index for column
a[1:3,[0,2]]

array([[3, 5],
       [4, 6]])

In [14]:
a

array([[1, 2, 3],
       [3, 4, 5],
       [4, 5, 6]])

### Broadcast
넘파이에서 형상이 다른 배열을 계산하기 위해서 지원하는 기능 (without explicit for-loop)

In [ ]:
A = np.array([[56.0, 0.0, 4.0, 68.0], 
              [1.2, 104.0, 52.0, 8.0], 
              [1.8, 135.0, 99.0, 0.9]])
print(A)

In [ ]:
cal = A.sum(axis=0)
print(cal)

In [ ]:
percentage = 100* A / cal #.reshape(1,4)
print(percentage)

### Stack

In [ ]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])

* 세로로 쌓기

In [ ]:
c = np.vstack((a,b))
print(c)
print(c.shape)

* 가로로 쌓기

In [ ]:
d = np.hstack((a,b))
print(d)

### 형변환

In [ ]:
x = np.array([-2.0, 1.2, 3.7])
y = x > 0
print(y)

In [ ]:
y = y.astype(np.int)
print(y)

## Noise

In [ ]:
x = np.arange(0, 6, 0.1) # 0에서 6까지 0.1 간격으로 생성
y = np.sin(x)

In [ ]:
y

In [ ]:
signal_length = y.shape[0]
print(signal_length)

In [ ]:
noise = np.random.normal(0, 1, signal_length)
y2 = y + 0.2* noise

* 참고 np.random.normal : 
random samples from a normal (Gaussian) distrubution

In [ ]:
plt.plot(x, y)
plt.plot(x, y2)
#plt.show()

### 배열 형태 변환

Create a 3x3 matrix with values ranging from 0 to 8

In [ ]:
Z = np.arange(9).reshape(3,3)
print(Z)

In [ ]:
A = np.random.rand(4, 3, 2)
print(A)

In [ ]:
A = A.reshape(12, 2)
print(A)

### 1차원 변환 ravel() vs. reshape() vs. flatten()
*  다차원 배열을 1차원으로 바꾸는 것

In [ ]:
B = A.ravel()
print(B.shape)

In [ ]:
C = A.flatten()
print(C.shape)

reshape을 이용한 구현

In [ ]:
# YOUR CODE HERE
#raise NotImplementedError()

### Random

#### np.random.choice

In [ ]:
np.random.seed(0)
p = np.array([0.1, 0.0, 0.7, 0.2])

In [ ]:
for i in range(10):
    index = np.random.choice([0, 1, 2, 3], p = p.ravel())
    print(i, index)

This means that you will pick the `index` according to the distribution: 
$P(index = 0) = 0.1, P(index = 1) = 0.0, P(index = 2) = 0.7, P(index = 3) = 0.2$.

In [ ]:
v =[0,0,0,0]
ntest = 1000
for i in range(ntest):
    idx = np.random.choice([0, 1, 2, 3], p = p.ravel())
    v[idx] += 1

#### np.random.permutation

In [ ]:
m1 = np.random.permutation(5)
print(m1)

* array shuffle하기 (1차원)

In [ ]:
X = np.array([10,20,30,40,50])
shuffled_X = X[m1]

In [ ]:
print(X)
print(shuffled_X)

* array shuffle하기 (2차원)

In [ ]:
x1 = [2, 4, 8, 10, 20]
x2 = [0.2,  0.4, -0.8, 1.0, -2.0]
X = np.transpose(np.vstack((x1, x2)))

In [ ]:
print(X)
print(X.shape)

In [ ]:
permutation = np.random.permutation(5)

In [ ]:
X_shuffle=  X[permutation]

In [ ]:
print(X_shuffle)

참고

* 100 numpy exercises, https://www.kaggle.com/utsav15/100-numpy-exercises
* Slicing and dicing, https://www.mbaskool.com/business-concepts/it-and-systems/13503-slicing-and-dicing.html#:~:text=Slicing%20and%20Dicing%20refers%20to,is%20achieved%20for%20proper%20analysis.